// src-vue/views/DynamicProxy/components/SettingDetail.vue
<template>
  <el-dialog
    v-model="visible"
    :title="setting.id ? 'Edit' : 'Add'"
    width="900px"
    @close="handleCancel"
  >
    <el-form
      ref="formRef"
      :model="formData"
      :rules="rules"
      label-width="120px"
    >
      <el-form-item label="启用" prop="enabled">
        <el-switch v-model="formData.enabled" />
      </el-form-item>

      <el-form-item label="配置类型" prop="type">
        <el-radio-group v-model="formData.type" @change="handleTypeChange">
          <el-radio label="exact">Exact</el-radio>
          <el-radio label="prefix">Prefix</el-radio>
          <el-radio label="regex">Regex</el-radio>
        </el-radio-group>
      </el-form-item>

      <el-form-item label="匹配条件" prop="from">
        <el-input v-model="fromUrl" @blur="handleFromBlur">
          <template #prepend>
            <el-select v-model="fromProtocol" style="width: 90px" @change="updateFromUrl">
              <el-option label="http://" value="http" />
              <el-option label="https://" value="https" />
            </el-select>
          </template>
          <template #append>
            <span style="cursor: pointer" @click="showTest = !showTest">Test</span>
          </template>
        </el-input>
      </el-form-item>

      <el-form-item v-if="showTest" label="Test" prop="test">
        <el-input v-model="testUrl">
          <template #append>
            <el-icon @click="showTest = false" style="cursor: pointer">
              <Close />
            </el-icon>
          </template>
        </el-input>
        <div v-if="testResult" :style="{ color: testResult.success ? '#67c23a' : '#f56c6c', marginTop: '4px', fontSize: '12px' }">
          {{ testResult.message }}
        </div>
      </el-form-item>

      <el-form-item label="代理目标" prop="to">
        <el-input v-model="toUrl" :disabled="formData.reqHook" @blur="handleToBlur">
          <template #prepend>
            <el-select v-model="toProtocol" :disabled="formData.reqHook" style="width: 90px" @change="updateToUrl">
              <el-option label="http://" value="http" />
              <el-option label="https://" value="https" />
              <el-option label="file://" value="file" />
            </el-select>
          </template>
          <template #append v-if="toProtocol === 'file'">
            <input
              ref="fileInputRef"
              type="file"
              webkitdirectory
              directory
              style="display: none"
              @change="handleSelectFile"
            />
            <el-button type="text" @click="triggerFileSelect">选择</el-button>
          </template>
        </el-input>
      </el-form-item>

      <el-form-item label="延迟" prop="delay">
        <el-input-number v-model="formData.delay" :min="0" />
      </el-form-item>

      <el-form-item label="修改请求参数" prop="reqHook">
        <el-switch v-model="formData.reqHook" />
      </el-form-item>

      <el-form-item v-if="formData.reqHook" label="代码" prop="reqHookCode">
        <CodeEditor v-model="formData.reqHookCode" />
      </el-form-item>

      <el-form-item label="修改响应结果" prop="resHook">
        <el-switch v-model="formData.resHook" />
      </el-form-item>

      <el-form-item v-if="formData.resHook" label="代码" prop="resHookCode">
        <CodeEditor v-model="formData.resHookCode" />
      </el-form-item>
    </el-form>

    <template #footer>
      <el-button @click="handleCancel">取消</el-button>
      <el-button type="primary" @click="handleOk">确定</el-button>
    </template>
  </el-dialog>
</template>

<script setup lang="ts">
import { ref, reactive, watch } from 'vue';
import { Close } from '@element-plus/icons-vue';
import type { FormInstance, FormRules } from 'element-plus';
import type { ProxySetting } from '../../../stores/global';
import CodeEditor from './CodeEditor.vue';

const props = defineProps<{
  setting: ProxySetting;
}>();

const emit = defineEmits<{
  ok: [setting: ProxySetting];
  cancel: [];
}>();

const visible = ref(true);
const formRef = ref<FormInstance>();
const showTest = ref(false);
const testUrl = ref('');
const testResult = ref<{ success: boolean; message: string } | null>(null);
const fileInputRef = ref<HTMLInputElement>();

const getInitReqChangeCode = () => `// 按需修改url、headers、body，可以返回具体的值，也可以返回一个Promise
async function reqHook({url, headers, body}) {
  return {url, headers, body};
}`;

const getInitResChangeCode = () => `// 按需修改headers、body，可以返回具体的值，也可以返回一个Promise
async function resHook(request, {code, headers, body}) {
  return {code, headers, body};
}`;

const formData = reactive<ProxySetting>({
  id: props.setting.id,
  enabled: props.setting.enabled !== false,
  type: props.setting.type || 'exact',
  from: props.setting.from || 'http://',
  to: props.setting.to || 'http://',
  reqHook: props.setting.reqHook || false,
  reqHookCode: props.setting.reqHookCode || getInitReqChangeCode(),
  resHook: props.setting.resHook || false,
  resHookCode: props.setting.resHookCode || getInitResChangeCode(),
  delay: props.setting.delay || 0,
});

const removeProtocol = (url: string) => url.replace(/^.*?:\/\//, '');
const getProtocol = (url: string) => url.replace(/(.*?):.*/, '$1');
const hasProtocol = (url: string) => ['http', 'https', 'file'].includes(getProtocol(url));

const fromProtocol = ref(getProtocol(formData.from));
const fromUrl = ref(removeProtocol(formData.from));
const toProtocol = ref(getProtocol(formData.to));
const toUrl = ref(removeProtocol(formData.to));

const updateFromUrl = () => {
  formData.from = `${fromProtocol.value}://${fromUrl.value}`;
};

const updateToUrl = () => {
  formData.to = `${toProtocol.value}://${toUrl.value}`;
};

const handleFromBlur = () => {
  if (hasProtocol(fromUrl.value)) {
    fromProtocol.value = getProtocol(fromUrl.value);
    fromUrl.value = removeProtocol(fromUrl.value);
  }
  updateFromUrl();
};

const handleToBlur = () => {
  if (hasProtocol(toUrl.value)) {
    toProtocol.value = getProtocol(toUrl.value);
    toUrl.value = removeProtocol(toUrl.value);
  }
  updateToUrl();
};

const triggerFileSelect = () => {
  fileInputRef.value?.click();
};

const handleSelectFile = (event: Event) => {
  const target = event.target as HTMLInputElement;
  const files = target.files;
  
  if (files && files.length > 0) {
    // 获取第一个文件的路径
    const file = files[0] as any;
    if (file.path) {
      // 如果选择的是文件夹，使用文件夹路径
      // 如果选择的是文件，使用文件路径
      let path = file.path;
      
      // 如果是文件夹中的文件，提取文件夹路径
      if (files.length > 1 || file.webkitRelativePath) {
        // 从 webkitRelativePath 中提取文件夹路径
        const relativePath = file.webkitRelativePath;
        if (relativePath) {
          const folderName = relativePath.split('/')[0];
          path = file.path.replace(new RegExp(`/${relativePath.split('/').slice(1).join('/')}$`), '');
          path = path.replace(new RegExp(`/${folderName}$`), '') + '/' + folderName;
        }
      }
      
      // 确保文件夹路径末尾有 /
      if (!path.endsWith('/')) {
        path += '/';
      }
      
      toUrl.value = path;
      updateToUrl();
    }
  }
  
  // 重置 input 以便可以重复选择同一个文件/文件夹
  target.value = '';
};

const testFrom = (testUrl: string, fromUrl: string, nowType: string) => {
  switch (nowType) {
    case 'regex':
      return new RegExp(fromUrl).test(testUrl);
    case 'prefix':
      return testUrl.startsWith(fromUrl);
    case 'exact':
    default:
      return testUrl === fromUrl;
  }
};

const validateTest = () => {
  if (testUrl.value) {
    const isMatch = testFrom(testUrl.value, formData.from, formData.type);
    if (isMatch) {
      testResult.value = { success: true, message: '✓ 匹配成功' };
    } else {
      testResult.value = { success: false, message: '✗ 匹配失败' };
    }
  } else {
    testResult.value = null;
  }
};

const handleTypeChange = () => {
  testResult.value = null;
  if (testUrl.value) {
    validateTest();
  }
};

const rules: FormRules = {
  from: [{ required: true, message: '必填', trigger: 'blur' }],
  to: [
    {
      required: true,
      validator: (rule, value, callback) => {
        if (!formData.reqHook && !value) {
          callback(new Error('必填'));
        } else {
          callback();
        }
      },
      trigger: 'blur',
    },
  ],
};

const handleOk = async () => {
  if (!formRef.value) return;
  
  await formRef.value.validate((valid) => {
    if (valid) {
      emit('ok', { ...formData });
    }
  });
};

const handleCancel = () => {
  emit('cancel');
};

watch(() => formData.reqHook, (val) => {
  if (val) {
    formRef.value?.clearValidate('to');
  }
});

// 监听 testUrl 变化，实时验证
watch(testUrl, () => {
  validateTest();
});

// 监听 formData.from 变化，实时验证
watch(() => formData.from, () => {
  if (testUrl.value) {
    validateTest();
  }
});
</script>

<style scoped>
:deep(.el-form-item__content) {
  line-height: normal;
}
</style>

// src/pages/DynamicProxy/SettingDetail/index.tsx
import { Form, Modal, Input, Select, Radio, Switch, Upload } from 'antd';
import { CloseOutlined } from '@ant-design/icons';
import React, { useState } from 'react';
import { ProxySetting } from '@/models/connect';
import HookCodeAce from './HookCodeAce';
import './index.less';

const {Option} = Select;
const RadioGroup = Radio.Group;
const FormItem = Form.Item;

const removeProtocol = (url: string) => url.replace(/^.*?:\/\//, '');
const getProtocol = (url: string) => url.replace(/(.*?):.*/, '$1');
const hasProtocol = (url: string) => ['http', 'https', 'file'].includes(getProtocol(url))

const formItemLayout = {
  labelCol: { span: 4 },
  wrapperCol: { span: 12 },
};

const getInitReqChangeCode = () => `// 按需修改url、headers、body，可以返回具体的值，也可以返回一个Promise
async function reqHook({url, headers, body}) {
  return {url, headers, body};
}`;

const getInitResChangeCode = () => `// 按需修改headers、body，可以返回具体的值，也可以返回一个Promise
async function resHook(request, {code, headers, body}) {
  return {code, headers, body};
}`;

const SettingDetail: React.FC<{setting: ProxySetting; onOk: any}> = ({
  setting,
  onOk
}) => {
  const [showTest, setShowTest] = useState(false);
  const [nowSetting, setNowSetting] = useState(setting);
  nowSetting.type = nowSetting.type || 'exact';
  nowSetting.from = nowSetting.from || 'http://';
  nowSetting.to = nowSetting.to || 'http://';
  nowSetting.enabled = nowSetting.enabled !== false;
  nowSetting.reqHook = nowSetting.reqHook || false;
  nowSetting.reqHookCode = nowSetting.reqHookCode || getInitReqChangeCode();
  nowSetting.resHook = nowSetting.resHook || false;
  nowSetting.resHookCode = nowSetting.resHookCode || getInitResChangeCode();
  nowSetting.delay = nowSetting.delay || 0;

  const {type, from, to, enabled, reqHook, reqHookCode, resHook, resHookCode, delay} = nowSetting;
  const [form] = Form.useForm();
  const disableTo = !!reqHook;

  const setSetting = (s: object) => setNowSetting(Object.assign(nowSetting, s));

  const selectFromProtocol = (
    <Select value={getProtocol(from)} style={{ width: 90 }} onChange={v => setSetting({from: `${v}://${removeProtocol(from)}`})}>
      <Option value="http">http://</Option>
      <Option value="https">https://</Option>
    </Select>
  );

  const selectToProtocol = (
    <Select disabled={disableTo} value={getProtocol(to)} style={{ width: 90 }} onChange={v => setSetting({to: `${v}://${removeProtocol(to)}`})}>
      <Option value="http">http://</Option>
      <Option value="https">https://</Option>
      <Option value="file">file://</Option>
    </Select>
  );

  function setFromToForm(value: string, field: string, oldValue: string) {
    let url = value.trim();
    if (hasProtocol(url)) {
      setSetting({[field]: url});
      url = removeProtocol(value.trim());
      form.setFieldsValue({[field]: url});
    } else {
      setSetting({[field]: `${getProtocol(oldValue)}://${url}`});
      form.setFieldsValue({[field]: url});
    }
    form.validateFields(['test']);
  }

  function onSelectFile({file}) {
    setFromToForm(file.originFileObj.path, 'to', to);
  }

  function testFrom(testUrl, fromUrl, nowType) {
    switch(nowType) {
      case 'regex':
        return new RegExp(fromUrl).test(testUrl);
      case 'prefix':
        return testUrl.startsWith(fromUrl);
      case 'exact':
      default:
        return testUrl === fromUrl;
    }
  }

  const onFinish = () => onOk(nowSetting);

  const renderAce = (codeKey: string) => (<HookCodeAce
    onChange={(value) => {
      form.setFieldsValue({[codeKey]: value});
      setSetting({[codeKey]: value});
    }}
  />);

  return (
    <Modal
      className='proxySettingDetail'
      title={setting.id ? 'Edit' : 'Add'}
      visible
      onOk={() => form.submit()}
      onCancel={() => onOk()}
    >
      <Form {...formItemLayout} form={form} onFinish={onFinish}>
        <FormItem
          label='启用'
          name='enabled'
          valuePropName='checked'
          initialValue={enabled}
        >
          <Switch onChange={checked => {
            form.setFieldsValue({enabled: checked});
            setSetting({enabled: checked});
          }} />
        </FormItem>
        <FormItem
          label='配置类型'
          name='type'
          initialValue={type}
        >
          <RadioGroup onChange={({target: {value}}) => {
            setSetting({type: value});
            form.setFieldsValue({type: value});
            form.validateFields(['test']);
          }}>
            <Radio value="exact">Exact</Radio>
            <Radio value="prefix">Prefix</Radio>
            <Radio value="regex">Regex</Radio>
          </RadioGroup>
        </FormItem>
        <FormItem
          label='匹配条件'
          name='from'
          rules={[{
            required: true,
            message: '必填'
          }]}
          initialValue={removeProtocol(from)}
        >
          <Input
            addonBefore={selectFromProtocol}
            addonAfter={<span onClick={() => setShowTest(!showTest)}>Test</span>}
            onChange={({target: {value}}) => setFromToForm(value, 'from', from)}
          />
        </FormItem>
        {showTest && <FormItem
          label='Test'
          name='test'
          initialValue={from}
          dependencies={['type', 'from']}
          rules={[({ getFieldValue }) => ({
            validator(rule, value) {
              return new Promise((resolve, reject) => {
                if (testFrom(value, nowSetting.from, nowSetting.type)) {
                  resolve();
                } else {
                  reject('Not match!');
                }
              });
            },
          })]}
        >
          <Input
            className='test'
            allowClear
            addonAfter={<CloseOutlined onClick={() => setShowTest(false)} />}
          />
        </FormItem>}
        <FormItem
          label='代理目标'
          name='to'
          rules={[{
            required: !disableTo && true,
            message: '必填'
          }]}
          initialValue={removeProtocol(to)}
        >
          <Input
            disabled={disableTo}
            addonBefore={selectToProtocol}
            addonAfter={to.startsWith('file://') && <Upload onChange={onSelectFile} fileList={[]}>选择</Upload>}
            onChange={({target: {value}}) => setFromToForm(value, 'to', to)}
          />
        </FormItem>

        <FormItem
          label='延迟'
          name='delay'
          rules={[{
            type: 'number',
            message: '只能填写数字'
          }]}
          initialValue={delay}
        >
          <Input
            onChange={({target: {value}}) => {
              const v = isNaN(Number(value)) ? delay : Number(value);
              form.setFieldsValue({delay: v});
              setSetting({delay: v});
            }}
          />
        </FormItem>

        <FormItem
          label='修改请求参数'
          name='reqHook'
          valuePropName='checked'
          initialValue={reqHook}
        >
          <Switch onChange={checked => {
            form.setFieldsValue({reqHook: checked});
            setSetting({reqHook: checked});
          }} />
        </FormItem>
        {reqHook && <FormItem
          label='代码'
          name='reqHookCode'
          initialValue={reqHookCode}
        >
          {renderAce('reqHookCode')}
        </FormItem>}

        <FormItem
          label='修改响应结果'
          name='resHook'
          valuePropName='checked'
          initialValue={resHook}
        >
          <Switch onChange={checked => {
            form.setFieldsValue({resHook: checked});
            setSetting({resHook: checked});
          }} />
        </FormItem>
        {resHook && <FormItem
          label='代码'
          name='resHookCode'
          initialValue={resHookCode}
        >
          {renderAce('resHookCode')}
        </FormItem>}
      </Form>
    </Modal>
  );
};

export default SettingDetail;
