// src/pages/DynamicProxy/index.tsx
import { Table, Button } from 'antd';
import React, { useState, useEffect } from 'react';
import { connect } from 'umi';
import { ConnectState, GlobalModelState, ProxySetting } from '@/models/connect';
import SettingDetail from './SettingDetail';
import { getProxySettings, updateProxySetting, addProxySetting, deleteProxySetting } from './service';

import './index.less';

const HttpList: React.FC<{global: GlobalModelState}> = ({
  global: {
    proxySettings
  }
}) => {
  const [nowSetting, setNowSetting] = useState<ProxySetting | null>(null);

  function onSave(setting: ProxySetting) {
    if (setting) {
      if (setting.id) {
        updateProxySetting(setting);
      } else {
        addProxySetting(setting);
      }
    }
    setNowSetting(null);
  }

  useEffect(() => {
    getProxySettings();
  }, []);

  const columns = [
    {
      title: '匹配方式',
      key: 'type',
      dataIndex: 'type',
      width: 70,
      render: (text: string) => text
    },
    {
      title: 'From',
      key: 'from',
      dataIndex: 'from',
      width: 300,
      render: (text: string) => text
    },
    {
      title: 'To',
      key: 'to',
      dataIndex: 'to',
      width: 300,
      render: (text: string) => text
    },
    {
      title: '操作',
      key: 'operation',
      dataIndex: 'operation',
      width: 150,
      className: 'operations',
      render: (text: string, setting: ProxySetting) => <>
        <a onClick={() => setNowSetting(setting)}>Edit</a>
        <a onClick={() => deleteProxySetting(setting)}>Delete</a>
        <a onClick={() => setNowSetting({...setting, id: undefined})}>Copy</a>
        <a onClick={() => onSave({...setting, enabled: !setting.enabled})}>{setting.enabled ? 'Disable' : 'Enable'}</a>
      </>
    }
  ];

  return (
    <>
      <Table
        rowKey='id'
        columns={columns}
        rowClassName={record => record.enabled ? '' : 'disabled'}
        dataSource={proxySettings}
        pagination={false}
        className='dynamicproxy'
        scroll={{ x: 'calc(100vw - 180px)', y: 'calc(100vh - 163px)' }}
      />
      <Button type='primary' onClick={() => setNowSetting({})}>Add</Button>
      {nowSetting && <SettingDetail setting={nowSetting} onOk={onSave} />}
    </>
  );
};

export default connect(({ global }: ConnectState) => ({
  global,
}))(HttpList);

// src-vue/views/DynamicProxy/index.vue
<template>
  <div>
    <el-table
      :data="proxySettings"
      row-key="id"
      :row-class-name="getRowClassName"
      class="dynamicproxy"
      height="calc(100vh - 180px)"
      style="width: 100%"
    >
      <el-table-column prop="type" label="匹配方式" width="100" />
      <el-table-column prop="from" label="From" min-width="200" />
      <el-table-column prop="to" label="To" min-width="200" />
      <el-table-column label="操作" width="320" class-name="operations">
        <template #default="{ row }">
          <div style="white-space: nowrap;">
            <el-button link type="primary" @click="editSetting(row)">Edit</el-button>
            <el-button link type="danger" @click="handleDelete(row)">Delete</el-button>
            <el-button link type="primary" @click="copySetting(row)">Copy</el-button>
            <el-button link type="primary" @click="toggleEnabled(row)">
              {{ row.enabled ? 'Disable' : 'Enable' }}
            </el-button>
          </div>
        </template>
      </el-table-column>
    </el-table>
    
    <div style="padding: 16px;">
      <el-button type="primary" @click="addSetting">Add</el-button>
    </div>

    <SettingDetail
      v-if="nowSetting"
      :setting="nowSetting"
      @ok="handleSave"
      @cancel="nowSetting = null"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { storeToRefs } from 'pinia';
import { useGlobalStore, type ProxySetting } from '../../stores/global';
import { getProxySettings, updateProxySetting, addProxySetting, deleteProxySetting } from '../../api/dynamicProxy';
import SettingDetail from './components/SettingDetail.vue';

const globalStore = useGlobalStore();
const { proxySettings } = storeToRefs(globalStore);

const nowSetting = ref<ProxySetting | null>(null);

const getRowClassName = ({ row }: { row: ProxySetting }) => {
  return row.enabled ? '' : 'disabled';
};

const editSetting = (setting: ProxySetting) => {
  nowSetting.value = { ...setting };
};

const copySetting = (setting: ProxySetting) => {
  const copied = { ...setting };
  delete copied.id;
  nowSetting.value = copied;
};

const addSetting = () => {
  nowSetting.value = {
    enabled: true,
    type: 'exact',
    from: 'http://',
    to: 'http://',
    reqHook: false,
    reqHookCode: '',
    resHook: false,
    resHookCode: '',
    delay: 0,
  };
};

const toggleEnabled = (setting: ProxySetting) => {
  handleSave({ ...setting, enabled: !setting.enabled });
};

const handleDelete = (setting: ProxySetting) => {
  deleteProxySetting(setting);
};

const handleSave = (setting: ProxySetting) => {
  if (setting) {
    if (setting.id) {
      updateProxySetting(setting);
    } else {
      addProxySetting(setting);
    }
  }
  nowSetting.value = null;
};

onMounted(() => {
  getProxySettings();
});
</script>

<style>
.dynamicproxy .disabled {
  opacity: 0.5;
}

.operations .el-button+.el-button {
  margin-left: 5px;
}
</style>
