// src/pages/HttpList/HttpPackageDetail/index.tsx
import { Modal, Tabs } from 'antd';
import React from 'react';
import ReactJson from 'react-json-view';
import { HttpPackage } from '@/models/connect';
import './index.less';

const TabPane = Tabs.TabPane;
const contentType = 'Content-Type';

function getBodyStr(req: any) {
  if (!req || !req.body) {
    return '';
  }
  return req.body.split ? req.body : JSON.stringify(req.body, null, 2);
}

function isJson(req: any) {
  return req?.headers && req.headers[contentType] && req.headers[contentType].toLowerCase().includes('json');
}

const HttpPackageDetail: React.FC<{detail: HttpPackage | null; onOk: () => void; getPath: any}> = ({
  detail,
  getPath,
  onOk
}) => {
  function getRequest() {
    return (
      <div className='httprequest'>
        {`${detail?.req.method} ${getPath(detail?.req.url)} HTTP/${detail?.req.httpVersion}`}
      </div>
    );
  }

  function getResponse() {
    return (
      <div className='httprequest'>
        {`HTTP/${detail?.res.httpVersion} ${detail?.res.statusCode} ${detail?.res.statusMessage}`}
      </div>
    );
  }

  function getHeader(req: any) {
    return (
      <div className='httpheader'>
        {Object.entries(req.headers || {}).map(([key, value]) => (
          <div key={key}>
            <span key={`${key}`}>{key}:</span>
            <span key={`${key}-${value}`}>{value}</span>
          </div>
        ))}
      </div>
    );
  }

  function getReqBody(str: string) {
    return <pre className='httpbody'>{str}</pre>;
  }

  function getBodyJson(jsonData) {
    let src = '';
    try {
      src = jsonData.split ? JSON.parse(jsonData) : jsonData
    } catch (error) {
      console.error(error);
    }
    return (
      <div className='httpbody'>
        {src ? <ReactJson src={src} /> : null}
      </div>
    );
  }

  function getResErr() {
    return <pre className='httpbody'>{detail?.res.err}</pre>;
  }

  function isGet() {
    return detail?.req.method.toLowerCase() === 'get';
  }

  function renderReq(req) {
    return (
      <>
        <div key='1'>
          请求
        </div>
        <div key='2'>
          <Tabs defaultActiveKey='request'>
            <TabPane tab='Request' key='request'>{getRequest()}</TabPane>
            <TabPane tab='Header' key='header'>{getHeader(req)}</TabPane>
            {isGet() || <TabPane tab='Body' key='body'>{getReqBody(getBodyStr(req))}</TabPane>}
            {!isGet() && isJson(req) && <TabPane tab='JSON Body' key='json'>{getBodyJson(req.body)}</TabPane>}
          </Tabs>
        </div>
      </>
    );
  }

  function renderRes(res) {
    return (
      <>
        <div key='3'>
          响应
        </div>
        <div key='4'>
          <Tabs defaultActiveKey='response'>
            <TabPane tab='Response' key='response'>{getResponse()}</TabPane>
            <TabPane tab='Header' key='header'>{getHeader(res)}</TabPane>
            {res.body && <TabPane tab='Body' key='body'>{getReqBody(getBodyStr(res))}</TabPane>}
            {isJson(res) && !res.err && <TabPane tab='JSON Body' key='json'>{getBodyJson(res.body)}</TabPane>}
            {res.err && <TabPane tab='Err' key='err'>{getResErr()}</TabPane>}
          </Tabs>
        </div>
      </>
    );
  }

  return detail && (
    <Modal
      className='httpdetail'
      title={<span className='ellipsis' title={detail.req.url}>{detail.req.url}</span>}
      visible
      onOk={onOk}
      onCancel={onOk}
    >
      {detail.req && renderReq(detail.req)}
      {detail.res && renderRes(detail.res)}
    </Modal>
  );
};

export default HttpPackageDetail;

// src-vue/views/HttpList/components/HttpPackageDetail.vue
<template>
  <el-dialog
    v-model="visible"
    :title="detail?.req.url"
    width="80%"
    class="httpdetail"
    @close="handleClose"
  >
    <div v-if="detail?.req">
      <h3>请求</h3>
      <el-tabs>
        <el-tab-pane label="Request">
          <div class="httprequest">
            {{ `${detail.req.method} ${getPath(detail.req.url)} HTTP/${detail.req.httpVersion}` }}
          </div>
        </el-tab-pane>
        <el-tab-pane label="Header">
          <div class="httpheader">
            <div v-for="[key, value] in Object.entries(detail.req.headers || {})" :key="key">
              <span>{{ key }}:</span>
              <span>{{ value }}</span>
            </div>
          </div>
        </el-tab-pane>
        <el-tab-pane v-if="!isGet" label="Body">
          <pre class="httpbody">{{ getBodyStr(detail.req) }}</pre>
        </el-tab-pane>
        <el-tab-pane v-if="!isGet && isJson(detail.req)" label="JSON Body">
          <div class="httpbody">
            <pre>{{ formatJson(detail.req.body) }}</pre>
          </div>
        </el-tab-pane>
      </el-tabs>
    </div>

    <div v-if="detail?.res">
      <h3>响应</h3>
      <el-tabs>
        <el-tab-pane label="Response">
          <div class="httprequest">
            {{ `HTTP/${detail.res.httpVersion} ${detail.res.statusCode} ${detail.res.statusMessage}` }}
          </div>
        </el-tab-pane>
        <el-tab-pane label="Header">
          <div class="httpheader">
            <div v-for="[key, value] in Object.entries(detail.res.headers || {})" :key="key">
              <span>{{ key }}:</span>
              <span>{{ value }}</span>
            </div>
          </div>
        </el-tab-pane>
        <el-tab-pane v-if="detail.res.body" label="Body">
          <pre class="httpbody">{{ getBodyStr(detail.res) }}</pre>
        </el-tab-pane>
        <el-tab-pane v-if="isJson(detail.res) && !detail.res.err" label="JSON Body">
          <div class="httpbody">
            <pre>{{ formatJson(detail.res.body) }}</pre>
          </div>
        </el-tab-pane>
        <el-tab-pane v-if="detail.res.err" label="Err">
          <pre class="httpbody">{{ detail.res.err }}</pre>
        </el-tab-pane>
      </el-tabs>
    </div>
  </el-dialog>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import { getPath } from '../../../utils/utils';
import type { HttpPackage } from '../../../stores/global';

const props = defineProps<{
  detail: HttpPackage | null;
}>();

const emit = defineEmits<{
  close: [];
}>();

const visible = ref(true);

const isGet = computed(() => {
  return props.detail?.req.method.toLowerCase() === 'get';
});

const contentType = 'Content-Type';

const isJson = (req: any) => {
  return req?.headers && req.headers[contentType] && req.headers[contentType].toLowerCase().includes('json');
};

const getBodyStr = (req: any) => {
  if (!req || !req.body) {
    return '';
  }
  return typeof req.body === 'string' ? req.body : JSON.stringify(req.body, null, 2);
};

const formatJson = (jsonData: any) => {
  try {
    const data = typeof jsonData === 'string' ? JSON.parse(jsonData) : jsonData;
    return JSON.stringify(data, null, 2);
  } catch (error) {
    console.error(error);
    return jsonData;
  }
};

const handleClose = () => {
  emit('close');
};
</script>

<style scoped>
.httpdetail h3 {
  margin: 20px 0 10px;
}

.httprequest {
  padding: 10px;
  background: #f5f5f5;
  border-radius: 4px;
  font-family: monospace;
}

.httpheader {
  padding: 10px;
}

.httpheader div {
  display: flex;
  margin-bottom: 8px;
}

.httpheader span:first-child {
  font-weight: bold;
  margin-right: 8px;
  min-width: 150px;
}

.httpbody {
  padding: 10px;
  background: #f5f5f5;
  border-radius: 4px;
  font-family: monospace;
  white-space: pre-wrap;
  word-break: break-all;
  max-height: 400px;
  overflow: auto;
}
</style>
